---
apiVersion: monitoring.openshift.io/v1
kind: AlertRelabelConfig
metadata:
  name: demote-receiver-alert
  namespace: openshift-monitoring
spec:
  configs:
  - sourceLabels: [alertname,severity]
    regex: 'AlertmanagerReceiversNotConfigured;warning'
    targetLabel: severity
    replacement: info