#!/bin/bash
# CHECK VARIABLE VALUES ARE BETWEEN DOUBLE QUOTES!

# OpenShift version (must be 4.x.z format)
# https://mirror.openshift.com/pub/openshift-v4/clients/ocp/
OPENSHIFT_VERSION="stable-4.20"

# Enter here your RHPDS Lab Top Level Route53 Domain excluding the dot prefix at the beginning. Example: .sandbox1234.opentlc.com
RHPDS_TOP_LEVEL_ROUTE53_DOMAIN=""

# Enter here your cluster name
CLUSTER_NAME="ocp"
    
# AWS credentials
## AWS Access Key ID
export AWS_ACCESS_KEY_ID=""
## AWS Secret Access Key
export AWS_SECRET_ACCESS_KEY=""

# AWS Region. Change according to your location
# https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html-single/installing_on_aws/index#installation-aws-public_installing-aws-account
export AWS_DEFAULT_REGION="eu-central-1"

# Public key to add to the OCP nodes for ssh.
# This value is optional, so just add a value if you want to add a key
# SSH_PUBLIC_KEY="$(cat ~/.ssh/id_rsa.pub | tr -d '\n')"
SSH_PUBLIC_KEY=""

# Enter Pull Secret given from RedHat OpenShift Cluster Manager site (https://console.redhat.com/openshift/downloads#tool-pull-secret) for an AWS IPI installation
# WARNING: FILL THE PULL SECRET BETWEEN SINGLE QUOTES HERE!
RHOCM_PULL_SECRET=''

# This is the base URL to download both CLI and installer. 
# You are not supposed to modify it unless you need to experiment nightly releases.
OCP_DOWNLOAD_BASE_URL="https://mirror.openshift.com/pub/openshift-v4/clients/ocp"

# Machines configuration
# https://aws.amazon.com/ec2/instance-types/
# https://aws.amazon.com/ec2/pricing/on-demand/
## 1) Normal worker => WORKER_INSTANCE_TYPE=m8i.2xlarge
## 2) Large Worker  => WORKER_INSTANCE_TYPE=m8i.4xlarge

# Option 1: Multi-node OCP
WORKER_INSTANCE_TYPE=m8i.4xlarge # Normal worker nodes
# https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/installing_on_aws/installation-config-parameters-aws#installation-configuration-parameters-optional-aws_installation-config-parameters-aws
# COMPUTE_VOLUME_SIZE=200 # Size in GB. Default is 120GB
WORKER_REPLICAS=1
MASTER_INSTANCE_TYPE=m8i.xlarge

# # Option 2: Single-node OCP
# WORKER_REPLICAS=0
# MASTER_INSTANCE_TYPE=m8i.4xlarge
# MASTER_REPLICAS=1

# OCP SSL Certificates and GitOps configuration
INSTALL_LETS_ENCRYPT_CERTIFICATES=true
INSTALL_OPENSHIFT_GITOPS=true

# OCP Lightspeed
INSTALL_OPENSHIFT_LIGHTSPEED=false
OLS_PROVIDER_NAME=""
OLS_PROVIDER_MODEL_NAME=""
OLS_PROVIDER_TYPE=""
OLS_PROVIDER_API_URL=""
OLS_PROVIDER_API_TOKEN=""

# ./aws-ocp4-install.sh ./aws-ocp4-config-labs